version: "3.9"

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:7.0-alpine3.17
    ports:
      - 5000:5000
    environment:      
      - PATH=/root/.dotnet/tools:$PATH
      - ASPNETCORE_ENVIRONMENT=Development
      - DBSETTINGS__HOST=db
      - DBSETTINGS__NAME=devdb
      - DBSETTINGS__USER=devuser
      - DBSETTINGS__PASSWORD=changeme
      - JWTSETTINGS__ACCESSSECRETKEY=VeryLongSuperSecureSecretKeyForJwts
      - JWTSETTINGS__REFRESHSECRETKEY=VeryLongRefreshSuperSecureSecretKeyForJwts
      - JWTSETTINGS__ISSUER=localhost
      - JWTSETTINGS__AUDIENCE=com.example.recipier
      - JWTSETTINGS__ACCESSTOKENLIFETIME=00:15:00
      - JWTSETTINGS__REFRESHTOKENLIFETIME=24:00:00
    volumes:
      - ./Api:/Api
      - ./Scripts:/Scripts
      - ~/.vsdbg:/remote_debugger:rw
    working_dir: /Api
    command: sh -c "/Scripts/wait-for-it.sh db:5432 -- dotnet watch run --project ./Api/Api.csproj --urls http://+:5000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine3.17
    ports:
      - 5432:5432
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
